//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainApplication.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainApplication.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new Extension.
        /// </summary>
        public static string BUTTON_CREATE_EXTENSION {
            get {
                return ResourceManager.GetString("BUTTON_CREATE_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new file name.
        /// </summary>
        public static string BUTTON_CREATE_PRIORITY_FILE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE_PRIORITY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create new Save.
        /// </summary>
        public static string BUTTON_CREATE_SAVE {
            get {
                return ResourceManager.GetString("BUTTON_CREATE_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pause all Saves.
        /// </summary>
        public static string BUTTON_PAUSE_ALL_SAVES {
            get {
                return ResourceManager.GetString("BUTTON_PAUSE_ALL_SAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resume all Saves.
        /// </summary>
        public static string BUTTON_RESUME_ALL_SAVES {
            get {
                return ResourceManager.GetString("BUTTON_RESUME_ALL_SAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start all Saves.
        /// </summary>
        public static string BUTTON_START_ALL_SAVES {
            get {
                return ResourceManager.GetString("BUTTON_START_ALL_SAVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a Save.
        /// </summary>
        public static string CHOICE_DESC_CREATE {
            get {
                return ResourceManager.GetString("CHOICE_DESC_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Application.
        /// </summary>
        public static string CHOICE_DESC_END {
            get {
                return ResourceManager.GetString("CHOICE_DESC_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove a Save.
        /// </summary>
        public static string CHOICE_DESC_REMOVE {
            get {
                return ResourceManager.GetString("CHOICE_DESC_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Save List.
        /// </summary>
        public static string CHOICE_DESC_SHOW_LIST {
            get {
                return ResourceManager.GetString("CHOICE_DESC_SHOW_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Run one or multiple Save(s).
        /// </summary>
        public static string CHOICE_DESC_START {
            get {
                return ResourceManager.GetString("CHOICE_DESC_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop one or multiple Save(s).
        /// </summary>
        public static string CHOICE_DESC_STOP {
            get {
                return ResourceManager.GetString("CHOICE_DESC_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Possible Actions List:.
        /// </summary>
        public static string CHOICE_DISPLAY {
            get {
                return ResourceManager.GetString("CHOICE_DISPLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have to complete all input !.
        /// </summary>
        public static string CREATE_COMPLETE_ALL_INPUTS {
            get {
                return ResourceManager.GetString("CREATE_COMPLETE_ALL_INPUTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type a name to the Save or &quot;cancel&quot; to cancel:.
        /// </summary>
        public static string CREATE_SAVE_ASK_NAME {
            get {
                return ResourceManager.GetString("CREATE_SAVE_ASK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A save already has this name..
        /// </summary>
        public static string CREATE_SAVE_ASK_NAME_RETRY {
            get {
                return ResourceManager.GetString("CREATE_SAVE_ASK_NAME_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type the Save path or &quot;cancel&quot; to cancel:.
        /// </summary>
        public static string CREATE_SAVE_ASK_SOURCE_URI {
            get {
                return ResourceManager.GetString("CREATE_SAVE_ASK_SOURCE_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The path is incorrect..
        /// </summary>
        public static string CREATE_SAVE_ASK_SOURCE_URI_RETRY {
            get {
                return ResourceManager.GetString("CREATE_SAVE_ASK_SOURCE_URI_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type the Save write path or &quot;cancel&quot; to cancel:.
        /// </summary>
        public static string CREATE_SAVE_ASK_TARGET_URI {
            get {
                return ResourceManager.GetString("CREATE_SAVE_ASK_TARGET_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The path is incorrect..
        /// </summary>
        public static string CREATE_SAVE_ASK_TARGET_URI_RETRY {
            get {
                return ResourceManager.GetString("CREATE_SAVE_ASK_TARGET_URI_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type backup type ( 1 - Complete | 2 - Differential ) or &quot;cancel&quot; to cancel:.
        /// </summary>
        public static string CREATE_SAVE_ASK_TYPE {
            get {
                return ResourceManager.GetString("CREATE_SAVE_ASK_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This backup type doesn&apos;t exist..
        /// </summary>
        public static string CREATE_SAVE_ASK_TYPE_RETRY {
            get {
                return ResourceManager.GetString("CREATE_SAVE_ASK_TYPE_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while creating your Save!.
        /// </summary>
        public static string CREATE_SAVE_ERROR {
            get {
                return ResourceManager.GetString("CREATE_SAVE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have reached the limit of 5 saves..
        /// </summary>
        public static string CREATE_SAVE_REACH_LIMIT {
            get {
                return ResourceManager.GetString("CREATE_SAVE_REACH_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Source Path.
        /// </summary>
        public static string CREATE_SAVE_SELECT_SOURCE {
            get {
                return ResourceManager.GetString("CREATE_SAVE_SELECT_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Target Path.
        /// </summary>
        public static string CREATE_SAVE_SELECT_TARGET {
            get {
                return ResourceManager.GetString("CREATE_SAVE_SELECT_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Save has been successfully created!.
        /// </summary>
        public static string CREATE_SAVE_SUCCESS {
            get {
                return ResourceManager.GetString("CREATE_SAVE_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One job Application is running, please stop them to run save(s) !.
        /// </summary>
        public static string ERROR_JOB_APPLICATION_RUNNING {
            get {
                return ResourceManager.GetString("ERROR_JOB_APPLICATION_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This extension already exist !.
        /// </summary>
        public static string EXTENSION_ADD_ASK_NAME_RETRY {
            get {
                return ResourceManager.GetString("EXTENSION_ADD_ASK_NAME_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type something or type enter to back to the menu.
        /// </summary>
        public static string GLOBAL_ASK_GO_TO_MENU {
            get {
                return ResourceManager.GetString("GLOBAL_ASK_GO_TO_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter name of Save or &quot;cancel&quot; to cancel:.
        /// </summary>
        public static string GLOBAL_ASK_SAVE_NAME {
            get {
                return ResourceManager.GetString("GLOBAL_ASK_SAVE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter name of Save or &quot;all&quot; to run all Saves or &quot;cancel&quot; to cancel:.
        /// </summary>
        public static string GLOBAL_ASK_SAVE_NAME_OR_ALL {
            get {
                return ResourceManager.GetString("GLOBAL_ASK_SAVE_NAME_OR_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string GLOBAL_CANCEL {
            get {
                return ResourceManager.GetString("GLOBAL_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You cannot remove running save..
        /// </summary>
        public static string GLOBAL_CANNOT_REMOVE_RUNNING_SAVE {
            get {
                return ResourceManager.GetString("GLOBAL_CANNOT_REMOVE_RUNNING_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string GLOBAL_CREATE {
            get {
                return ResourceManager.GetString("GLOBAL_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done..
        /// </summary>
        public static string GLOBAL_DONE {
            get {
                return ResourceManager.GetString("GLOBAL_DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Extensions will be Encrypted.
        /// </summary>
        public static string GLOBAL_ENCRYPT_EXTENSIONS_GUI {
            get {
                return ResourceManager.GetString("GLOBAL_ENCRYPT_EXTENSIONS_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string GLOBAL_NAME {
            get {
                return ResourceManager.GetString("GLOBAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Performing Save....
        /// </summary>
        public static string GLOBAL_PERFORMING_SAVE {
            get {
                return ResourceManager.GetString("GLOBAL_PERFORMING_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of all priority Files.
        /// </summary>
        public static string GLOBAL_PRIORITY_FILES_GUI {
            get {
                return ResourceManager.GetString("GLOBAL_PRIORITY_FILES_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Progression.
        /// </summary>
        public static string GLOBAL_PROGRESSION {
            get {
                return ResourceManager.GetString("GLOBAL_PROGRESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This save is already running..
        /// </summary>
        public static string GLOBAL_SAVE_ALREADY_RUN {
            get {
                return ResourceManager.GetString("GLOBAL_SAVE_ALREADY_RUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This save doesn&apos;t exist..
        /// </summary>
        public static string GLOBAL_SAVE_NAME_NOT_EXIST {
            get {
                return ResourceManager.GetString("GLOBAL_SAVE_NAME_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Choice:.
        /// </summary>
        public static string GLOBAL_SELECT_CHOICE {
            get {
                return ResourceManager.GetString("GLOBAL_SELECT_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect Choice..
        /// </summary>
        public static string GLOBAL_SELECT_CHOICE_RETRY {
            get {
                return ResourceManager.GetString("GLOBAL_SELECT_CHOICE_RETRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please Select Language (en-US, fr-FR):.
        /// </summary>
        public static string GLOBAL_SELECT_LANGUAGE {
            get {
                return ResourceManager.GetString("GLOBAL_SELECT_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please Select Language !.
        /// </summary>
        public static string GLOBAL_SELECT_LANGUAGE_GUI {
            get {
                return ResourceManager.GetString("GLOBAL_SELECT_LANGUAGE_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please Select Save File Type !.
        /// </summary>
        public static string GLOBAL_SELECT_SAVE_FILE_TYPE_GUI {
            get {
                return ResourceManager.GetString("GLOBAL_SELECT_SAVE_FILE_TYPE_GUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The language selected is : en-US.
        /// </summary>
        public static string GLOBAL_SELECTED_LANGUAGE {
            get {
                return ResourceManager.GetString("GLOBAL_SELECTED_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source.
        /// </summary>
        public static string GLOBAL_SOURCE {
            get {
                return ResourceManager.GetString("GLOBAL_SOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State.
        /// </summary>
        public static string GLOBAL_STATE {
            get {
                return ResourceManager.GetString("GLOBAL_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Target.
        /// </summary>
        public static string GLOBAL_TARGET {
            get {
                return ResourceManager.GetString("GLOBAL_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type of Save.
        /// </summary>
        public static string GLOBAL_TYPE {
            get {
                return ResourceManager.GetString("GLOBAL_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to EasySave !.
        /// </summary>
        public static string GLOBAL_WELCOME {
            get {
                return ResourceManager.GetString("GLOBAL_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new Extension.
        /// </summary>
        public static string HOME_ADD_EXTENSION {
            get {
                return ResourceManager.GetString("HOME_ADD_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add new File.
        /// </summary>
        public static string HOME_ADD_PRIORITY_FILE {
            get {
                return ResourceManager.GetString("HOME_ADD_PRIORITY_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home EasySave.
        /// </summary>
        public static string PAGE_HOME_TITLE {
            get {
                return ResourceManager.GetString("PAGE_HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Logs.
        /// </summary>
        public static string PAGE_LOGS_TITLE {
            get {
                return ResourceManager.GetString("PAGE_LOGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home Page.
        /// </summary>
        public static string PAGE_NAVIGATION_HOME_TITLE {
            get {
                return ResourceManager.GetString("PAGE_NAVIGATION_HOME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Logs.
        /// </summary>
        public static string PAGE_NAVIGATION_LOGS_TITLE {
            get {
                return ResourceManager.GetString("PAGE_NAVIGATION_LOGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saves Page.
        /// </summary>
        public static string PAGE_NAVIGATION_SAVES_TITLE {
            get {
                return ResourceManager.GetString("PAGE_NAVIGATION_SAVES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saves Manager.
        /// </summary>
        public static string PAGE_SAVES_TITLE {
            get {
                return ResourceManager.GetString("PAGE_SAVES_TITLE", resourceCulture);
            }
        }
    }
}
