name: .NET 6.0 DesktopApplication

on:
  push:
    branches: [ master ]
    paths:
    - 'DesktopApplication/**'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore
      run: dotnet restore DesktopApplication
        
    - name: Publish
      run: dotnet publish DesktopApplication -r win-x64 -p:PublishSingleFile=true --configuration Release --self-contained true --no-restore
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: DesktopApplication-win-x64-b${{ github.run_number }}
        path : ${{ github.workspace }}\DesktopApplication\bin\Release\net6.0-windows\win-x64\publish\
      
