name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  console_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ConsoleApplication --no-restore
    - name: Test
      run: dotnet test ConsoleApplication --no-build --verbosity normal
    - name: Run app
      run: dotnet run ConsoleApplication
