name: .NET 6.0 GuiApplication

on:
  push:
    branches: [ master ]
    paths:
    - 'GuiApplication/**'
    - 'MainApplication/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'GuiApplication/**'
    - 'MainApplication/**'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-2022
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore
      run: dotnet restore GuiApplication
        
    - name: Publish
      run: dotnet publish GuiApplication -r win10-x64 -p:PublishSingleFile=true --configuration Release --self-contained true --no-restore
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: GuiApplication-win10-x64-b${{ github.run_number }}
        path : ${{ github.workspace }}\GuiApplication\bin\Release\net6.0-windows\win10-x64\publish\
      
