name: .NET 6.0 ConsoleApplication

on:
  push:
    branches: [ master ]
    paths:
    - 'ConsoleApplication/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ConsoleApplication
  
    - name: Build
      run: dotnet build ConsoleApplication --configuration Release

    - name: Publish win-x64
      run: dotnet publish ConsoleApplication -r win-x64 -p:PublishSingleFile=true --configuration Release --self-contained true --no-restore

    - name: Publish linux-x64
      run: dotnet publish ConsoleApplication -r linux-x64 -p:PublishSingleFile=true --configuration Release --self-contained true --no-restore

    - name: Publish osx-x64
      run: dotnet publish ConsoleApplication -r osx-x64 -p:PublishSingleFile=true --configuration Release --self-contained true --no-restore
        
    - name: Upload win-x64 artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: ConsoleApplication-win-x64-b${{ github.run_number }}
        path : ${{ github.workspace }}\ConsoleApplication\bin\Debug\net6.0\win-x64\publish\ConsoleApplication.exe
        
    - name: Upload linux-x64 artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: ConsoleApplication-linux-x64-b${{ github.run_number }}
        path : ${{ github.workspace }}\ConsoleApplication\bin\Debug\net6.0\linux-x64\publish\ConsoleApplication
        
    - name: Upload osx-x64 artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: ConsoleApplication-osx-x64-b${{ github.run_number }}
        path : ${{ github.workspace }}\ConsoleApplication\bin\Debug\net6.0\osx-x64\publish\ConsoleApplication
